spring.datasource.url=jdbc:postgresql://localhost/quepasa
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.generate-ddl=true

#spring.freemarker.expose-request-attributes=true
spring.mustache.expose-request-attributes=true